server:
  port: 8082
spring:
  servlet:
    multipart:
      max-file-size: 6MB
      max-request-size: 6MB
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  application:
    name: autodeploy

  datasource:
    url: jdbc:mysql://localhost:3306/lincoln_douyin_bff?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  # jpa配置
#  jpa:
#    database: MYSQL
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    open-in-view: false
#
#  # redis本地配置
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    #    password:               # Redis服务器连接密码（默认为空）
#    database: 1
#    timeout: 5000s  # 连接超时时长（毫秒）
#    jedis:
#      pool:
#        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
#        max-idle: 8  #连接池中的最大空闲连接
#        max-wait: -1s #连接池最大阻塞等待时间（使用负值表示没有限制)
#        min-idle: 0  #连接池中的最小空闲连接

#  data:
#    redis:
#      repositories:
#        enabled: false

#schedule 开关
schedule:
  enabled: false